FROM python:3.9

LABEL description="Base container for CPU models"

RUN apt-get update && apt-get install -y htop dnsutils bc vim curl unzip nano

RUN pip install --upgrade pip

RUN apt-get install curl unzip -y && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -f ./awscliv2.zip


RUN pip install torch configparser configargparse boto3 torchvision scikit-learn tqdm

RUN echo "alias ll='ls -alh --color=auto'" >> /root/.bashrc

